---
# Global monitoring policy (single source of truth)

cpu_threshold: 50
memory_threshold: 80
latency_threshold: 50

enable_cloud_checks: true
enable_network_checks: true
enable_alerting: true
monitoring_mode: "hybrid"

# Discord Notifications
enable_discord_alerts: true
discord_webhook_url: "https://discord.com/api/webhooks/1523466194353520701/48ym2zfbzoBz5dyjU2HKXGa4TBNaUzLBZl3u9R9gmGENHcBfgpyWvfVwvQiAcF_RKOu6
"
