---
# Role-specific variables (higher priority than defaults)

monitoring_environment: "hybrid"

network_domain: "cisco-ios"
cloud_domains:
  - aws
  - azure
  - gcp
  - private_cloud

alert_mode: "debug"   # can later become slack/email/webhook

log_level: "info"
