name: Network Health Monitoring

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  health-check:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Install Cisco Collection
        run: |
          ansible-galaxy collection install cisco.ios

      - name: Run Ansible Playbook
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          ansible-playbook health_check.yml | tee ansible-output.txt

      - name: Upload Ansible Output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ansible-output
          path: ansible-output.txt

      - name: Send Monitoring Summary
        if: always()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python scripts/send_mon_summary.py
