---
name: Network Health Monitoring

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  health-check:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint

      - name: Install Cisco Collection
        run: |
          ansible-galaxy collection install cisco.ios
       
      - name: Show yamllint version
        run: |
          yamllint --version
          python --version

      - name: Inspect defaults file
        run: |
           cat -A roles/health_checks/defaults/main.yml

      - name: Inspect line endings
        run: |
          file roles/health_checks/defaults/main.yml
          xxd roles/health_checks/defaults/main.yml | head

      - name: Check all YAML line endings
        run: |
          find . -name "*.yml" -o -name "*.yaml" | while read f; do
          echo "===== $f ====="
          file "$f"
          done

      - name: Verify line endings after checkout
        run: |
          echo "===== handlers ====="
          file roles/health_checks/handlers/main.yml
          cat -A roles/health_checks/handlers/main.yml | head

      - name: Convert CRLF to LF
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          find roles -name "*.yml" -exec dos2unix {} \;
    
      - name: Run YAML Lint
        run: |
          yamllint .

      - name: Run Ansible Lint 
        run: |
          ansible-lint

      - name: Create Vault Password File
        run: |
          mkdir -p .vault
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault/vault_pass.txt
          chmod 600 .vault/vault_pass.txt
    
      - name: Run Ansible Playbook
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          ansible-playbook \
           --vault-password-file .vault/vault_pass.txt \
           health_check.yml | tee ansible-output.txt
           
      # TEMPORARY - Verify alerts.jsonl is created
      - name: Show monitoring log
        if: always()
        run: |
          echo "===== monitoring_logs ====="
          ls -R monitoring_logs || true

          echo ""
          echo "===== alerts.jsonl ====="
          cat monitoring_logs/alerts.jsonl || true
          
      - name: Upload Ansible Output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ansible-output
          path: ansible-output.txt

      - name: Send Monitoring Summary
        if: always()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python scripts/send_mon_summary.py
